// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxupy-R3Wvy7_FCBq0YoHpEwV48NbHuC8',
    appId: '1:606939825382:web:5b9d1fbdf096ff196c2727',
    messagingSenderId: '606939825382',
    projectId: 'oru-assignment',
    authDomain: 'oru-assignment.firebaseapp.com',
    storageBucket: 'oru-assignment.appspot.com',
    measurementId: 'G-QCT8KVQFBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYLZHs4bPoZ1fxhuwSkdUPMs8pFR4DN2U',
    appId: '1:606939825382:android:9292ea082d4375376c2727',
    messagingSenderId: '606939825382',
    projectId: 'oru-assignment',
    storageBucket: 'oru-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjsUAtLY98da1KIn4AUCtpRuCwq-oZ4X4',
    appId: '1:606939825382:ios:fba922e4cbc6fb7a6c2727',
    messagingSenderId: '606939825382',
    projectId: 'oru-assignment',
    storageBucket: 'oru-assignment.appspot.com',
    androidClientId: '606939825382-d9s7shl56j8ebnh1e4jvnssuqov53828.apps.googleusercontent.com',
    iosClientId: '606939825382-92cm2ea9j861d052224g49gtottjq8uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.oru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjsUAtLY98da1KIn4AUCtpRuCwq-oZ4X4',
    appId: '1:606939825382:ios:24990547615feb0d6c2727',
    messagingSenderId: '606939825382',
    projectId: 'oru-assignment',
    storageBucket: 'oru-assignment.appspot.com',
    androidClientId: '606939825382-d9s7shl56j8ebnh1e4jvnssuqov53828.apps.googleusercontent.com',
    iosClientId: '606939825382-8237k3mctfttv21lrqq9m8s9ergoohoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.oru.RunnerTests',
  );
}
